SetFactory("OpenCASCADE");

// Generated by scripts/generate_geometry.py.
// Units: meters.

chord = {chord_m};
span = {span_m};
half_span = span / 2.0;
cyl_r = {cylinder_radius_m};
cyl_x = {cylinder_x_m};
cyl_z = {cylinder_z_m};

upstream = {farfield_upstream_m};
downstream = {farfield_downstream_m};
side = {farfield_side_m};
top = {farfield_top_m};
ground_z = {ground_z_m};

base_size = {base_size_m};
wing_size = {wing_size_m};
cyl_size = {cylinder_size_m};
near_wall_size = {near_wall_size_m};
ground_refine_size = {ground_refine_size_m};
wake_refine_size = {wake_refine_size_m};

// Domain: x streamwise, y spanwise, z vertical.
Box(1) = {-upstream, -half_span - side, ground_z,
          chord + upstream + downstream, span + 2.0 * side, top - ground_z};

// Thin aerodynamic volume used as an initial robust Gmsh target.
// The airfoil surface is represented by imported cross-section points
// in the generated .geo file below this template header.
{airfoil_point_block}

Curve Loop(12001) = {{airfoil_curve_ids}};
Plane Surface(12002) = {12001};
Extrude {0, span, 0} {
  Surface{12002};
}

wing_volume() = Volume In BoundingBox {{airfoil_x_min_m} - 1e-5, -1e-6, {airfoil_z_min_m} - 1e-5,
                                       {airfoil_x_max_m} + 1e-5, span + 1e-6, {airfoil_z_max_m} + 1e-5};

{cylinder_block}

fluid() = BooleanDifference{ Volume{1}; Delete; }{ Volume{wing_volume()}; {cylinder_boolean_volume} Delete; };

Physical Volume("fluid") = {fluid()};
Physical Surface("wing") = Surface In BoundingBox {{airfoil_x_min_m} - 1e-5, -1e-6, {airfoil_z_min_m} - 1e-5,
                                                   {airfoil_x_max_m} + 1e-5, span + 1e-6, {airfoil_z_max_m} + 1e-5};
{cylinder_physical_surface}
Physical Surface("inlet") = Surface In BoundingBox {-upstream - 1e-6, -half_span - side - 1e-6, ground_z - 1e-6,
                                                    -upstream + 1e-6, half_span + side + 1e-6, top + 1e-6};
Physical Surface("outlet") = Surface In BoundingBox {chord + downstream - 1e-6, -half_span - side - 1e-6, ground_z - 1e-6,
                                                     chord + downstream + 1e-6, half_span + side + 1e-6, top + 1e-6};
Physical Surface("ground") = Surface In BoundingBox {-upstream - 1e-6, -half_span - side - 1e-6, ground_z - 1e-6,
                                                     chord + downstream + 1e-6, half_span + side + 1e-6, ground_z + 1e-6};
Physical Surface("farfield") = Surface In BoundingBox {-upstream - 1e-6, -half_span - side - 1e-6, top - 1e-6,
                                                       chord + downstream + 1e-6, half_span + side + 1e-6, top + 1e-6};
Physical Surface("side_ymin") = Surface In BoundingBox {-upstream - 1e-6, -half_span - side - 1e-6, ground_z - 1e-6,
                                                        chord + downstream + 1e-6, -half_span - side + 1e-6, top + 1e-6};
Physical Surface("side_ymax") = Surface In BoundingBox {-upstream - 1e-6, half_span + side - 1e-6, ground_z - 1e-6,
                                                        chord + downstream + 1e-6, half_span + side + 1e-6, top + 1e-6};

{refinement_field_block}

Mesh.CharacteristicLengthMin = cyl_size;
Mesh.CharacteristicLengthMax = base_size;
Mesh.MeshSizeFromCurvature = 20;
Mesh.Algorithm3D = 10;
Mesh.ElementOrder = 1;
Mesh.Optimize = 0;
Mesh.OptimizeNetgen = 0;
Mesh.SaveAll = 0;
